config/routes.rb
Rails.application.routes.draw do

  resources :gardens do
    resources :plants, only: :create
  end
  resources :plants, only: :destroy

  resources :plants, only: [] do
    resources :plant_tags, only: [:new, :create]

  end
  resources :plant_tags, only: :destroy

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags, dependent: :destroy
  has_many :tags, through: :plant_tags

  validates :name, presence: true
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag
  validates :plant, uniqueness: { scope: :tag, message: "You can't add several times same tag" }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags
  has_many :plants, through: :plant_tags
  # validates :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController

  def new
    @plant = Plant.find(params[:plant_id])
    @plant_tag = PlantTag.new
  end

  def create
    @plant = Plant.find(params[:plant_id])
    @tags = Tag.find(params[:plant_tag][:tag])
    @tags.each do |tag|
      plant_tag = PlantTag.new
      plant_tag.plant = @plant
      plant_tag.tag = tag
      plant_tag.save
    end
    redirect_to garden_path(@plant.garden)
  end

  def destroy
    @plant_tag = PlantTag.find(params[:id])
    @plant_tag.destroy
    redirect_to garden_path(@plant_tag.plant.garden)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  # POST   /gardens/:garden_id/plants
  def create
    @plant = Plant.new(plant_params)
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@plant.garden)
    else
      render 'gardens/show' # render 'gardens/show.html.erb'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <h1>Editing Garden</h1>
      <%= render 'form', garden: @garden %>
      <br>
      <%= link_to 'Show', @garden %> |
      <%= link_to 'Back', gardens_path %>
      </div>
    </div>
  </div>

app/views/gardens/index.html.erb
<h1 class="text-center mt-4">All the gardens</h1>
<table class="table mt-4">
  <thead class="thead-light">
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Banner_Url</th>
      <th colspan="3"></th>
      <!-- <th scope="col">Handle</th> -->
  </thead>
  <tbody>
    <% count = 0 %>
    <% @gardens.each do |garden| %>
    <% count+= 1 %>
    <tr>
      <th scope="row"> <%= count %></th>
      <td> <%= garden.name %></td>
      <td> <%= garden.banner_url %></td>
      <td><%= link_to 'Show', garden %></td>
      <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
      <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>
<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @garden.banner_url %>')">
  <h1><%= @garden.name %></h1>
</div>

<div class="container">
  <div class="row">
    <% @garden.plants.each do |plant| %>
      <div class="col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= plant.image_url %>');">
          <div class="card-tags">
            <% plant.plant_tags.each do |plant_tag| %>
              <span>
                <%= plant_tag.tag.name %>
                <%= link_to plant_tag_path(plant_tag), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fas fa-times"></i>
                <% end %>
              </span>
            <% end %>
            <%= link_to new_plant_plant_tag_path(plant) do %>
              <i class="fas fa-plus"></i>
            <% end %>
          </div>
          <div class="card-description">
            <h2><%= plant.name %></h2>
          </div>
          <%= link_to "+", plant_path(plant), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h4>Add a plant:</h4>
      <%= simple_form_for [ @garden, @plant ] do |f| %>
        <%= f.input :name, placeholder: "Palm tree" %>
        <%= f.input :image_url, placeholder: "https://raw.githubusercontent.com/lewagon/fullstack-images/master/rails/parks-and-plants/philo.jpg" %>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
      <button class="btn btn-secondary toggle-form">Toggle form</button>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!-- < %= javascript_include_tag "application" %> -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <h1>Add new tag for <%= @plant.name %></h1>

      <%= simple_form_for [@plant, @plant_tag] do |f| %>
        <%= f.input :tag, collection: Tag.all, input_html: { multiple: true, class: 'multiple-select' }, include_hidden: false %>
        <%= f.submit "Add tag", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>